"""
Step 4 — write the DATA CARD.

A data card is the one-page "know your dataset cold" summary: how many subjects,
how the classes balance, where the labels came from, and — most importantly —
the limitations that will bite you later if you forget them. The Week-3 brief
calls this "the spine of the Project 1 writeup," so unlike the follow-along
figures, the output here (DATA_CARD.md) IS committed.

This script computes every number from the data on disk (nothing hard-coded) and
renders DATA_CARD.md, so the card can never drift from the dataset.

Run:  python data_card.py        # writes DATA_CARD.md next to this script
"""

import os

from utils import (list_records, rhythm_spans, has_signal, HERE, DATA_DIR,
                   C2017_DIR)

CARD = os.path.join(HERE, "DATA_CARD.md")


def afdb_stats():
    """Everything the card needs about the MIT-BIH AFib Database."""
    recs = list_records()
    time_by_rhythm = {}            # rhythm → samples
    episodes_by_rhythm = {}        # rhythm → count
    per_record = []                # (rec, hours, afib_fraction, has_signal)
    fs = 250
    for rec in recs:
        spans, fs = rhythm_spans(rec)
        total = sum(e - s for s, e, _ in spans)
        afib = sum(e - s for s, e, nm in spans if nm == "AFib")
        per_record.append((rec, total / fs / 3600,
                           afib / total if total else 0.0, has_signal(rec)))
        for s, e, nm in spans:
            time_by_rhythm[nm] = time_by_rhythm.get(nm, 0) + (e - s)
            episodes_by_rhythm[nm] = episodes_by_rhythm.get(nm, 0) + 1
    return recs, fs, time_by_rhythm, episodes_by_rhythm, per_record


def window_stats():
    """Per-window class balance, read back from the windowed CSV if it exists."""
    path = os.path.join(DATA_DIR, "windows_30s.csv")
    if not os.path.exists(path):
        return None
    counts, total = {}, 0
    with open(path) as f:
        next(f)                                   # header
        for line in f:
            label = line.split(",")[3]
            counts[label] = counts.get(label, 0) + 1
            total += 1
    return counts, total


def c2017_stats():
    path = os.path.join(C2017_DIR, "REFERENCE.csv")
    if not os.path.exists(path):
        return None
    names = {"N": "Normal", "A": "AFib", "O": "Other", "~": "Noisy"}
    counts, total = {}, 0
    for line in open(path):
        code = line.strip().split(",")[1]
        nm = names.get(code, code)
        counts[nm] = counts.get(nm, 0) + 1
        total += 1
    return counts, total


def pct(part, whole):
    return f"{100*part/whole:.1f}%" if whole else "—"


def render():
    recs, fs, time_by_rhythm, episodes, per_record = afdb_stats()
    total_samples = sum(time_by_rhythm.values())
    total_hours = total_samples / fs / 3600
    with_sig = [r for r in per_record if r[3]]
    no_sig = [r[0] for r in per_record if not r[3]]
    afib_pcts = sorted((r[2] for r in per_record), reverse=True)

    L = []
    add = L.append
    add("# Data Card — Project 1 (AFib Detection)\n")
    add("> Auto-generated by `data_card.py` from the data on disk. "
        "Do not edit by hand.\n")

    # ── afdb ──
    add("## Primary dataset — MIT-BIH Atrial Fibrillation Database (`afdb`)\n")
    add("| Field | Value |")
    add("|---|---|")
    add(f"| Records / subjects | {len(recs)} (one ~10 h recording per subject) |")
    add(f"| Records with signal | {len(with_sig)} "
        f"(2 are annotation-only: {', '.join(no_sig)}) |")
    add(f"| Channels | 2 ECG leads (ECG1, ECG2) |")
    add(f"| Sampling rate | {fs} Hz |")
    add(f"| Total duration | {total_hours:.0f} h |")
    add(f"| Label source | Cardiologist rhythm annotations (`.atr`) |")
    add(f"| Beat source | Machine-detected QRS (`.qrs`) — *not* hand-verified |")
    add("")

    add("### Class balance — by recording time\n")
    add("| Rhythm | Hours | Share | Episodes |")
    add("|---|---|---|---|")
    for nm in sorted(time_by_rhythm, key=time_by_rhythm.get, reverse=True):
        hrs = time_by_rhythm[nm] / fs / 3600
        add(f"| {nm} | {hrs:.1f} | {pct(time_by_rhythm[nm], total_samples)} "
            f"| {episodes[nm]} |")
    add("")

    add("### AFib burden is wildly uneven across subjects\n")
    add(f"- Most AFib-heavy record: **{pct(afib_pcts[0], 1)}** of its time in AFib")
    add(f"- Least: **{pct(afib_pcts[-1], 1)}**")
    add(f"- Median across records: **{pct(afib_pcts[len(afib_pcts)//2], 1)}**")
    add("- AFib is *paroxysmal* — it starts and stops within a record, so a "
        "detector must work **within** a recording, not just label whole "
        "subjects.\n")

    # ── windows ──
    win = window_stats()
    if win:
        counts, total = win
        add("### Derived: 30 s windows (the Week-4 training table)\n")
        add(f"Built by `window_labels.py` → `data/windows_30s.csv` "
            f"({total:,} windows, majority label).\n")
        add("| Label | Windows | Share |")
        add("|---|---|---|")
        for nm in sorted(counts, key=counts.get, reverse=True):
            add(f"| {nm} | {counts[nm]:,} | {pct(counts[nm], total)} |")
        add("")

    # ── challenge 2017 ──
    c = c2017_stats()
    if c:
        counts, total = c
        add("## Secondary dataset — PhysioNet/CinC Challenge 2017\n")
        add(f"Short single-lead strips (~9–60 s, 300 Hz), one label each. "
            f"{total:,} labelled recordings.\n")
        add("| Label | Recordings | Share |")
        add("|---|---|---|")
        for nm in ("Normal", "AFib", "Other", "Noisy"):
            if nm in counts:
                add(f"| {nm} | {counts[nm]:,} | {pct(counts[nm], total)} |")
        add("")

    # ── limitations ──
    add("## Known limitations (read before modelling)\n")
    add("1. **Only 23 signal subjects in afdb** — tiny by ML standards; "
        "per-subject splits are essential or the model memorises patients.")
    add("2. **Severe class imbalance, two ways** — AFib is ~37% of afdb time "
        "but concentrated in a few subjects; windowing inherits this.")
    add("3. **Machine-detected beats** (`.qrs`) — RR-based features carry "
        "detector error, not just physiology.")
    add("4. **Boundary windows are ambiguous** — a 30 s window spanning an "
        "onset is part-Normal/part-AFib; its label is a *rule*, not ground "
        "truth (see `window_labels.py`).")
    add("5. **Only 4 rhythms are labelled** in afdb (Normal, AFib, AFlutter, "
        "AV-junctional); everything else falls into the dominant span.")
    add("6. **Two datasets, two label schemes** — afdb has per-sample rhythm "
        "spans; Challenge-2017 has one verdict per strip incl. a *Noisy* class "
        "afdb has no equivalent for.")
    add("7. **Domain shift** — afdb is clean Holter ECG; Challenge-2017 is "
        "short, single-lead, and noisier. Good afdb numbers ≠ wrist-ready.\n")

    return "\n".join(L)


def main():
    text = render()
    with open(CARD, "w") as f:
        f.write(text)
    print(f"Wrote {CARD} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
